backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "productos"
    label: "Productos"
    files:
      - file: "data/products.json"
        label: "Listado"
        name: "listado"
        fields:
          - label: "Productos"
            name: "items"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Nombre", name: "name", widget: "string" }
              - { label: "Descripción", name: "desc", widget: "string", required: false }
              - { label: "Precio", name: "price", widget: "number", value_type: "int", required: false }
              - { label: "Categoría", name: "category", widget: "select", options: ["albumes","lotes","sueltas"] }
              - { label: "Badge", name: "badge", widget: "string", required: false }
              - { label: "Tags (separadas por coma)", name: "tags", widget: "list", required: false }
              - { label: "Imagen", name: "image", widget: "image", required: false }
